package com.peanut.dao.mapper;

import com.peanut.pojo.AddRequest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AddRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table add_request
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table add_request
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    int insert(AddRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table add_request
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    int insertSelective(AddRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table add_request
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    AddRequest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table add_request
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    int updateByPrimaryKeySelective(AddRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table add_request
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    int updateByPrimaryKey(AddRequest record);

    int checkRepetition(AddRequest record);

    List<AddRequest> selectByToId(String userId);

    Integer updateById(@Param("id") Integer id,@Param("isRead") Integer isRead);

    AddRequest selectByUserIdAndFriendId(@Param("userId") String userId, @Param("friendId") String friendId);
}