package com.peanut.dao.mapper;

import com.peanut.pojo.Comment;
import com.peanut.pojo.vo.CommentSimpleEntity;
import com.peanut.pojo.vo.PostCommentRel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    int updateByPrimaryKey(Comment record);
    List<PostCommentRel> getCommentPostRel(@Param("size") Integer size);

    List<CommentSimpleEntity> getSimpleCommentsByPostId(@Param("id") Integer id);

    CommentSimpleEntity getSimpleCommentById(@Param("id") Integer id);

    Integer getUserIdByCommentId(@Param("commentId") Integer commentId);
}