package com.peanut.dao.mapper;

import com.peanut.pojo.Crowd;

public interface CrowdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    int insert(Crowd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    int insertSelective(Crowd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    Crowd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    int updateByPrimaryKeySelective(Crowd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    int updateByPrimaryKey(Crowd record);
}