package com.peanut.dao.mapper;

import com.peanut.pojo.CrowdInfoRel;

public interface CrowdInfoRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_info_rel
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_info_rel
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    int insert(CrowdInfoRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_info_rel
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    int insertSelective(CrowdInfoRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_info_rel
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    CrowdInfoRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_info_rel
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    int updateByPrimaryKeySelective(CrowdInfoRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_info_rel
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    int updateByPrimaryKey(CrowdInfoRel record);
}