package com.peanut.dao.mapper;

import com.peanut.pojo.CrowdMsg;

public interface CrowdMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_msg
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_msg
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    int insert(CrowdMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_msg
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    int insertSelective(CrowdMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_msg
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    CrowdMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_msg
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    int updateByPrimaryKeySelective(CrowdMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_msg
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CrowdMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_msg
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    int updateByPrimaryKey(CrowdMsg record);
}