package com.peanut.dao.mapper;

import com.peanut.pojo.CrowdUserRel;

public interface CrowdUserRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_user_rel
     *
     * @mbg.generated Mon Nov 27 00:14:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_user_rel
     *
     * @mbg.generated Mon Nov 27 00:14:40 CST 2017
     */
    int insert(CrowdUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_user_rel
     *
     * @mbg.generated Mon Nov 27 00:14:40 CST 2017
     */
    int insertSelective(CrowdUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_user_rel
     *
     * @mbg.generated Mon Nov 27 00:14:40 CST 2017
     */
    CrowdUserRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_user_rel
     *
     * @mbg.generated Mon Nov 27 00:14:40 CST 2017
     */
    int updateByPrimaryKeySelective(CrowdUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crowd_user_rel
     *
     * @mbg.generated Mon Nov 27 00:14:40 CST 2017
     */
    int updateByPrimaryKey(CrowdUserRel record);
}