package com.peanut.dao.mapper;

import com.peanut.pojo.GroupMember;

public interface GroupMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    int insert(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    int insertSelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    GroupMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    int updateByPrimaryKeySelective(GroupMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_member
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    int updateByPrimaryKey(GroupMember record);
}