package com.peanut.dao.mapper;

import com.peanut.pojo.Post;
import com.peanut.pojo.vo.PostMain;
import com.peanut.pojo.vo.PostSimpleEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Mon Nov 27 21:43:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Mon Nov 27 21:43:39 CST 2017
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Mon Nov 27 21:43:39 CST 2017
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Mon Nov 27 21:43:39 CST 2017
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Mon Nov 27 21:43:39 CST 2017
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Mon Nov 27 21:43:39 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post
     *
     * @mbg.generated Mon Nov 27 21:43:39 CST 2017
     */
    int updateByPrimaryKey(Post record);

    List<PostSimpleEntity> getPostSimpleList();

    List<PostSimpleEntity> getTopList(@Param("size") Integer size);

    List<PostSimpleEntity> getBrowserList(@Param("size") Integer size);

    List<PostSimpleEntity> getLikeList(@Param("size") Integer size);

    List<PostSimpleEntity> getRecentList(@Param("size") Integer size);

    List<PostSimpleEntity> getCommentList(@Param("size") Integer size);

    List<PostSimpleEntity> getTopAll();

    List<PostSimpleEntity> getMyPostById(@Param("uid") Integer uid);

    PostSimpleEntity getPostSimpleById(@Param("id") Integer id);

    void increaseViewNum(@Param("id") Integer id);

    void increaseLikeNum(@Param("id") Integer id);
}