package com.peanut.dao.mapper;

import com.peanut.pojo.PrivateLetter;
import com.peanut.pojo.vo.PrivateLetterEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PrivateLetterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_letter
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_letter
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    int insert(PrivateLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_letter
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    int insertSelective(PrivateLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_letter
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    PrivateLetter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_letter
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    int updateByPrimaryKeySelective(PrivateLetter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_letter
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    int updateByPrimaryKey(PrivateLetter record);

    List<PrivateLetterEntity> getPrivateLetterByUserId(@Param("userId") Integer userId);
}