package com.peanut.dao.mapper;

import com.peanut.pojo.UserMsg;

public interface UserMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    int insert(UserMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    int insertSelective(UserMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    UserMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    int updateByPrimaryKeySelective(UserMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(UserMsg record);
}