package com.peanut.dao.mapper;

import com.peanut.chat.pojo.vo.FriendVo;
import com.peanut.chat.pojo.vo.UserVo;
import com.peanut.pojo.User;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    int updateByPrimaryKey(User record);

    User selectByStuId(@Param("stuId") String stuId);

    User selectByNickName(@Param("nickName") String nickName);

    List<FriendVo> selectByStuIds(@Param("stuIds") List<String> stuIds);

    void updateLastLogin(@Param("stuId") String stuId,@Param("time") Date time);

    FriendVo selectFriendById(String toId);

    int updatePersonalInfo(UserVo record);
}