package com.peanut.dao.mapper;

import com.peanut.chat.pojo.vo.MsgVo;
import com.peanut.pojo.UserMsgRel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserMsgRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg_rel
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg_rel
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    int insert(UserMsgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg_rel
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    int insertSelective(UserMsgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg_rel
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    UserMsgRel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg_rel
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    int updateByPrimaryKeySelective(UserMsgRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_msg_rel
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    int updateByPrimaryKey(UserMsgRel record);

    Integer updateStateByUuId(@Param("uuid") String uuid);

    List<MsgVo> getUnreadMsg(@Param("stuId") String stuId);
}