package com.peanut.pojo;

public class AddRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_request.id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_request.from_id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    private String fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_request.to_id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    private String toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_request.type
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_request.is_read
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    private Byte isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column add_request.complete
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    private Byte complete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_request.id
     *
     * @return the value of add_request.id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_request.id
     *
     * @param id the value for add_request.id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_request.from_id
     *
     * @return the value of add_request.from_id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public String getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_request.from_id
     *
     * @param fromId the value for add_request.from_id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_request.to_id
     *
     * @return the value of add_request.to_id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public String getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_request.to_id
     *
     * @param toId the value for add_request.to_id
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public void setToId(String toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_request.type
     *
     * @return the value of add_request.type
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_request.type
     *
     * @param type the value for add_request.type
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_request.is_read
     *
     * @return the value of add_request.is_read
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public Byte getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_request.is_read
     *
     * @param isRead the value for add_request.is_read
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column add_request.complete
     *
     * @return the value of add_request.complete
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public Byte getComplete() {
        return complete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column add_request.complete
     *
     * @param complete the value for add_request.complete
     *
     * @mbg.generated Mon Nov 27 00:12:13 CST 2017
     */
    public void setComplete(Byte complete) {
        this.complete = complete;
    }
}