package com.peanut.pojo;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.post_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.publish_date
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    private Date publishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.is_reply
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    private Byte isReply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    private Integer replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.is_sensitive
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    private Byte isSensitive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.post_id
     *
     * @return the value of comment.post_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.post_id
     *
     * @param postId the value for comment.post_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.publish_date
     *
     * @return the value of comment.publish_date
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.publish_date
     *
     * @param publishDate the value for comment.publish_date
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.is_reply
     *
     * @return the value of comment.is_reply
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public Byte getIsReply() {
        return isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.is_reply
     *
     * @param isReply the value for comment.is_reply
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public void setIsReply(Byte isReply) {
        this.isReply = isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_id
     *
     * @return the value of comment.reply_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_id
     *
     * @param replyId the value for comment.reply_id
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.is_sensitive
     *
     * @return the value of comment.is_sensitive
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public Byte getIsSensitive() {
        return isSensitive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.is_sensitive
     *
     * @param isSensitive the value for comment.is_sensitive
     *
     * @mbg.generated Mon Nov 27 00:13:59 CST 2017
     */
    public void setIsSensitive(Byte isSensitive) {
        this.isSensitive = isSensitive;
    }
}