package com.peanut.pojo;

public class CrowdMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_msg.id
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_msg.crowd_id
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    private Integer crowdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_msg.content
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_msg.id
     *
     * @return the value of crowd_msg.id
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_msg.id
     *
     * @param id the value for crowd_msg.id
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_msg.crowd_id
     *
     * @return the value of crowd_msg.crowd_id
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    public Integer getCrowdId() {
        return crowdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_msg.crowd_id
     *
     * @param crowdId the value for crowd_msg.crowd_id
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    public void setCrowdId(Integer crowdId) {
        this.crowdId = crowdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_msg.content
     *
     * @return the value of crowd_msg.content
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_msg.content
     *
     * @param content the value for crowd_msg.content
     *
     * @mbg.generated Mon Nov 27 00:14:36 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }
}