package com.peanut.pojo;

public class Crowd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd.id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd.owner_id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd.crowd_name
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    private String crowdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd.crowd_card
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    private String crowdCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd.current_notice_id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    private Integer currentNoticeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd.crowd_pic
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    private String crowdPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd.person_num
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    private Integer personNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd.id
     *
     * @return the value of crowd.id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd.id
     *
     * @param id the value for crowd.id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd.owner_id
     *
     * @return the value of crowd.owner_id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd.owner_id
     *
     * @param ownerId the value for crowd.owner_id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd.crowd_name
     *
     * @return the value of crowd.crowd_name
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public String getCrowdName() {
        return crowdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd.crowd_name
     *
     * @param crowdName the value for crowd.crowd_name
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public void setCrowdName(String crowdName) {
        this.crowdName = crowdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd.crowd_card
     *
     * @return the value of crowd.crowd_card
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public String getCrowdCard() {
        return crowdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd.crowd_card
     *
     * @param crowdCard the value for crowd.crowd_card
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public void setCrowdCard(String crowdCard) {
        this.crowdCard = crowdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd.current_notice_id
     *
     * @return the value of crowd.current_notice_id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public Integer getCurrentNoticeId() {
        return currentNoticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd.current_notice_id
     *
     * @param currentNoticeId the value for crowd.current_notice_id
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public void setCurrentNoticeId(Integer currentNoticeId) {
        this.currentNoticeId = currentNoticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd.crowd_pic
     *
     * @return the value of crowd.crowd_pic
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public String getCrowdPic() {
        return crowdPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd.crowd_pic
     *
     * @param crowdPic the value for crowd.crowd_pic
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public void setCrowdPic(String crowdPic) {
        this.crowdPic = crowdPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd.person_num
     *
     * @return the value of crowd.person_num
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public Integer getPersonNum() {
        return personNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd.person_num
     *
     * @param personNum the value for crowd.person_num
     *
     * @mbg.generated Mon Nov 27 00:14:08 CST 2017
     */
    public void setPersonNum(Integer personNum) {
        this.personNum = personNum;
    }

    @Override
    public String toString() {
        return "Crowd{" +
                "id=" + id +
                ", ownerId=" + ownerId +
                ", crowdName='" + crowdName + '\'' +
                ", crowdCard='" + crowdCard + '\'' +
                ", currentNoticeId=" + currentNoticeId +
                ", crowdPic='" + crowdPic + '\'' +
                ", personNum=" + personNum +
                '}';
    }
}