package com.peanut.pojo;

import java.util.Date;

public class CrowdInfoRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_info_rel.id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_info_rel.from_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    private Integer fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_info_rel.crowd_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    private Integer crowdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_info_rel.sending_time
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    private Date sendingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_info_rel.to_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    private Integer toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_info_rel.msg_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    private Integer msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crowd_info_rel.is_read
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    private Boolean isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_info_rel.id
     *
     * @return the value of crowd_info_rel.id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_info_rel.id
     *
     * @param id the value for crowd_info_rel.id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_info_rel.from_id
     *
     * @return the value of crowd_info_rel.from_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_info_rel.from_id
     *
     * @param fromId the value for crowd_info_rel.from_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_info_rel.crowd_id
     *
     * @return the value of crowd_info_rel.crowd_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public Integer getCrowdId() {
        return crowdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_info_rel.crowd_id
     *
     * @param crowdId the value for crowd_info_rel.crowd_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public void setCrowdId(Integer crowdId) {
        this.crowdId = crowdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_info_rel.sending_time
     *
     * @return the value of crowd_info_rel.sending_time
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public Date getSendingTime() {
        return sendingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_info_rel.sending_time
     *
     * @param sendingTime the value for crowd_info_rel.sending_time
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public void setSendingTime(Date sendingTime) {
        this.sendingTime = sendingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_info_rel.to_id
     *
     * @return the value of crowd_info_rel.to_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_info_rel.to_id
     *
     * @param toId the value for crowd_info_rel.to_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_info_rel.msg_id
     *
     * @return the value of crowd_info_rel.msg_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_info_rel.msg_id
     *
     * @param msgId the value for crowd_info_rel.msg_id
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crowd_info_rel.is_read
     *
     * @return the value of crowd_info_rel.is_read
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crowd_info_rel.is_read
     *
     * @param isRead the value for crowd_info_rel.is_read
     *
     * @mbg.generated Mon Nov 27 00:14:22 CST 2017
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }
}