package com.peanut.pojo;

public class GroupMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.gourp_id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    private Integer gourpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_member.member_id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.id
     *
     * @return the value of group_member.id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.id
     *
     * @param id the value for group_member.id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.gourp_id
     *
     * @return the value of group_member.gourp_id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    public Integer getGourpId() {
        return gourpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.gourp_id
     *
     * @param gourpId the value for group_member.gourp_id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    public void setGourpId(Integer gourpId) {
        this.gourpId = gourpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_member.member_id
     *
     * @return the value of group_member.member_id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_member.member_id
     *
     * @param memberId the value for group_member.member_id
     *
     * @mbg.generated Mon Nov 27 00:20:53 CST 2017
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}