package com.peanut.pojo;

import java.util.Date;

public class PrivateLetter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_letter.id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_letter.from_id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    private Integer fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_letter.to_id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    private Integer toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_letter.sending_time
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    private Date sendingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_letter.content
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_letter.is_read
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    private Byte isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_letter.id
     *
     * @return the value of private_letter.id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_letter.id
     *
     * @param id the value for private_letter.id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_letter.from_id
     *
     * @return the value of private_letter.from_id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_letter.from_id
     *
     * @param fromId the value for private_letter.from_id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_letter.to_id
     *
     * @return the value of private_letter.to_id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_letter.to_id
     *
     * @param toId the value for private_letter.to_id
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_letter.sending_time
     *
     * @return the value of private_letter.sending_time
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public Date getSendingTime() {
        return sendingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_letter.sending_time
     *
     * @param sendingTime the value for private_letter.sending_time
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public void setSendingTime(Date sendingTime) {
        this.sendingTime = sendingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_letter.content
     *
     * @return the value of private_letter.content
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_letter.content
     *
     * @param content the value for private_letter.content
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_letter.is_read
     *
     * @return the value of private_letter.is_read
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public Byte getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_letter.is_read
     *
     * @param isRead the value for private_letter.is_read
     *
     * @mbg.generated Mon Nov 27 00:16:49 CST 2017
     */
    public void setIsRead(Byte isRead) {
        this.isRead = isRead;
    }

    @Override
    public String toString() {
        return "PrivateLetter{" +
                "id=" + id +
                ", fromId=" + fromId +
                ", toId=" + toId +
                ", sendingTime=" + sendingTime +
                ", content='" + content + '\'' +
                ", isRead=" + isRead +
                '}';
    }
}