package com.peanut.pojo;

import com.peanut.chat.pojo.vo.FriendVo;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.stu_id
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private String stuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickname
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.head_pic
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private String headPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.declaration
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private String declaration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.personal_introduction
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private String personalIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.regist_date
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastest_login
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private Date lastestLogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastest_publish
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    private Date lastestPublish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */

    private String state;

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.stu_id
     *
     * @return the value of user.stu_id
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.stu_id
     *
     * @param stuId the value for user.stu_id
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickname
     *
     * @return the value of user.nickname
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickname
     *
     * @param nickname the value for user.nickname
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.head_pic
     *
     * @return the value of user.head_pic
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public String getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.head_pic
     *
     * @param headPic the value for user.head_pic
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setHeadPic(String headPic) {
        this.headPic = headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.declaration
     *
     * @return the value of user.declaration
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public String getDeclaration() {
        return declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.declaration
     *
     * @param declaration the value for user.declaration
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setDeclaration(String declaration) {
        this.declaration = declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.personal_introduction
     *
     * @return the value of user.personal_introduction
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public String getPersonalIntroduction() {
        return personalIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.personal_introduction
     *
     * @param personalIntroduction the value for user.personal_introduction
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setPersonalIntroduction(String personalIntroduction) {
        this.personalIntroduction = personalIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.regist_date
     *
     * @return the value of user.regist_date
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.regist_date
     *
     * @param registDate the value for user.regist_date
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastest_login
     *
     * @return the value of user.lastest_login
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public Date getLastestLogin() {
        return lastestLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastest_login
     *
     * @param lastestLogin the value for user.lastest_login
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setLastestLogin(Date lastestLogin) {
        this.lastestLogin = lastestLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastest_publish
     *
     * @return the value of user.lastest_publish
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public Date getLastestPublish() {
        return lastestPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastest_publish
     *
     * @param lastestPublish the value for user.lastest_publish
     *
     * @mbg.generated Mon Nov 27 00:18:05 CST 2017
     */
    public void setLastestPublish(Date lastestPublish) {
        this.lastestPublish = lastestPublish;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", stuId='" + stuId + '\'' +
                ", nickname='" + nickname + '\'' +
                ", password='" + password + '\'' +
                ", headPic='" + headPic + '\'' +
                ", sex='" + sex + '\'' +
                ", declaration='" + declaration + '\'' +
                ", birthday=" + birthday +
                ", personalIntroduction='" + personalIntroduction + '\'' +
                ", registDate=" + registDate +
                ", lastestLogin=" + lastestLogin +
                ", lastestPublish=" + lastestPublish +
                '}';
    }

    public FriendVo cover() {
        FriendVo vo = new FriendVo();
        vo.setStuId(this.stuId);
        vo.setBirthday(this.birthday);
        vo.setDeclaration(this.declaration);
        vo.setHeadPic(this.headPic);
        vo.setLastestLogin(this.lastestLogin);
        vo.setNickName(this.nickname);
        vo.setPersonalIntroduction(this.personalIntroduction);
        vo.setSex(this.sex);
        return vo;
    }
}