package com.peanut.pojo;

import com.peanut.chat.pojo.vo.MsgVo;

public class UserMsg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_msg.id
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_msg.content
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    private String content = "";
    private String uuid;
    private String fileName;
    private Integer msgType;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public Integer getMsgType() {
        return msgType;
    }

    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_msg.id
     *
     * @param id the value for user_msg.id
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_msg.content
     *
     * @return the value of user_msg.content
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_msg.content
     *
     * @param content the value for user_msg.content
     *
     * @mbg.generated Mon Nov 27 00:17:13 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    public void cover(MsgVo vo){
        content = vo.getMsg();
        uuid = vo.getUuid();
        fileName = vo.getFileName();
        msgType = vo.getMsgType();
    }
}