package com.peanut.pojo;

import com.peanut.chat.pojo.vo.MsgVo;

import java.util.Date;

public class UserMsgRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_msg_rel.id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_msg_rel.from_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    private String fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_msg_rel.to_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    private String toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_msg_rel.msg_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    private Integer msgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_msg_rel.sending_time
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    private Integer sendingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_msg_rel.is_read
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    private Boolean isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_msg_rel.id
     *
     * @return the value of user_msg_rel.id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_msg_rel.id
     *
     * @param id the value for user_msg_rel.id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_msg_rel.from_id
     *
     * @return the value of user_msg_rel.from_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public String getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_msg_rel.from_id
     *
     * @param fromId the value for user_msg_rel.from_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public void setFromId(String fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_msg_rel.to_id
     *
     * @return the value of user_msg_rel.to_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public String getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_msg_rel.to_id
     *
     * @param toId the value for user_msg_rel.to_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public void setToId(String toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_msg_rel.msg_id
     *
     * @return the value of user_msg_rel.msg_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public Integer getMsgId() {
        return msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_msg_rel.msg_id
     *
     * @param msgId the value for user_msg_rel.msg_id
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public void setMsgId(Integer msgId) {
        this.msgId = msgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_msg_rel.sending_time
     *
     * @return the value of user_msg_rel.sending_time
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public Integer getSendingTime() {
        return sendingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_msg_rel.sending_time
     *
     * @param sendingTime the value for user_msg_rel.sending_time
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public void setSendingTime(Integer sendingTime) {
        this.sendingTime = sendingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_msg_rel.is_read
     *
     * @return the value of user_msg_rel.is_read
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_msg_rel.is_read
     *
     * @param isRead the value for user_msg_rel.is_read
     *
     * @mbg.generated Mon Nov 27 00:17:18 CST 2017
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    public void cover(MsgVo vo, Integer msgId){
        this.fromId = vo.getUserId();
        this.toId = vo.getFriendId();
        this.isRead = false;
        this.msgId = msgId;
        this.sendingTime = (int)(System.currentTimeMillis() / 1000);
    }
}