package com.peanut.pojo;

public class UserOnline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.id
     *
     * @mbg.generated Mon Nov 27 00:17:24 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.stu_id
     *
     * @mbg.generated Mon Nov 27 00:17:24 CST 2017
     */
    private Integer stuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.id
     *
     * @return the value of user_online.id
     *
     * @mbg.generated Mon Nov 27 00:17:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.id
     *
     * @param id the value for user_online.id
     *
     * @mbg.generated Mon Nov 27 00:17:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.stu_id
     *
     * @return the value of user_online.stu_id
     *
     * @mbg.generated Mon Nov 27 00:17:24 CST 2017
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.stu_id
     *
     * @param stuId the value for user_online.stu_id
     *
     * @mbg.generated Mon Nov 27 00:17:24 CST 2017
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }
}